# Generated by Django 6.0.1 on 2026-01-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_recipe_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='food',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recipe'),
        ),
    ]
