# Generated by Django 6.0.1 on 2026-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_ingredient_ingredient_food_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(models.F('name'), name='unique_recipe_name'),
        ),
    ]
