# Generated by Django 6.0.1 on 2026-01-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_recipe_unique_recipe_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='unique_food'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'food'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(models.F('name'), name='unique_unit_name'),
        ),
    ]
