# Generated by Django 6.0.1 on 2026-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_unique_food_ingredient_unique_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1),
        ),
    ]
